day1=first
day2=second
day3=third
day4=fourth
day5=fifth
day6=sixth
day7=seventh
day8=eighth
day9=ninth
day10=tenth
day11=eleventh
day12=twelfth

gift1=a partridge in a pear tree
gift2=two turtle doves
gift3=three French Hens
gift4=four Calling Birds
gift5=five Golden Rings
gift6=six Geese a Laying
gift7=seven Swans a Swimming
gift8=eight Maids a Milking
gift9=nine Ladies Dancing
gift10=ten Lords a Leaping
gift11=eleven Pipers Piping
gift12=twelve Drummers Drumming

firstLine=On the %s day of Christmas my true love sent to me:
and=and
space=\u0020
newline=\n
doubleNewline=\n\n